testing:
  hostname: sysops.webonary.work
  configFile: ~/.ssh/config
  stage: test
  # NB: set the "branch" you want to deploy to webonary.work
  branch: Issue-171
  deploy_path: /var/www/sites/webonary.work

staging:
  hostname: sysops.webonary.work
  configFile: ~/.ssh/config
  stage: staging
  branch: develop
  deploy_path: /var/www/sites/webonary.work

production:
  hostname: sysops.webonary.org
  configFile: ~/.ssh/config
  stage: production
  branch: master
  deploy_path: /var/www/sites/webonary.org
